blank_issues_enabled: false
contact_links:
  - name: Request a new provider or report bug with an existing provider
    url: https://github.com/am-abdulmueed
    about: EXTREMELY IMPORTANT - Please do not report any provider bugs here or request new providers. This repository does not contain any providers. Please find the appropriate repository and report your issue there or join the discord.
  - name: Instagram
    url: https://instagram.com/pluginstream.app
    about: Join our instagram for faster support on smaller issues.
 - name: Telegram
    url: https://t.me/+XGfvoIQctp9jZjlk
    about: Join our telegram for faster support on smaller issues.